// Code generated by "stringer -type=Type"; DO NOT EDIT.

package layer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccA-0]
	_ = x[AccB-1]
	_ = x[Beard-2]
	_ = x[Beard1-3]
	_ = x[Beard2-4]
	_ = x[BeastEars-5]
	_ = x[Body-6]
	_ = x[Cloak-7]
	_ = x[Cloak1-8]
	_ = x[Cloak2-9]
	_ = x[Clothing-10]
	_ = x[Clothing1-11]
	_ = x[Clothing2-12]
	_ = x[Ears-13]
	_ = x[Eyebrows-14]
	_ = x[Eyes-15]
	_ = x[Face-16]
	_ = x[FacialMark-17]
	_ = x[FrontHair-18]
	_ = x[FrontHair1-19]
	_ = x[FrontHair2-20]
	_ = x[Glasses-21]
	_ = x[Head-22]
	_ = x[Mouth-23]
	_ = x[Nose-24]
	_ = x[RearHair-25]
	_ = x[RearHair1-26]
	_ = x[RearHair2-27]
	_ = x[Tail-28]
	_ = x[Tail1-29]
	_ = x[Tail2-30]
	_ = x[Wing-31]
	_ = x[Wing1-32]
	_ = x[Wing2-33]
}

const _Type_name = "AccAAccBBeardBeard1Beard2BeastEarsBodyCloakCloak1Cloak2ClothingClothing1Clothing2EarsEyebrowsEyesFaceFacialMarkFrontHairFrontHair1FrontHair2GlassesHeadMouthNoseRearHairRearHair1RearHair2TailTail1Tail2WingWing1Wing2"

var _Type_index = [...]uint8{0, 4, 8, 13, 19, 25, 34, 38, 43, 49, 55, 63, 72, 81, 85, 93, 97, 101, 111, 120, 130, 140, 147, 151, 156, 160, 168, 177, 186, 190, 195, 200, 204, 209, 214}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
