// Code generated by "stringer -type=Type"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Human-0]
	_ = x[Vampire-1]
	_ = x[Woke-2]
	_ = x[Zombie-3]
	_ = x[HumanNaked-4]
	_ = x[VampireNaked-5]
	_ = x[WokeNaked-6]
	_ = x[ZombieNaked-7]
}

const _Type_name = "HumanVampireWokeZombieHumanNakedVampireNakedWokeNakedZombieNaked"

var _Type_index = [...]uint8{0, 5, 12, 16, 22, 32, 44, 53, 64}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
