// Code generated by "stringer -type=Type"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Hum-0]
	_ = x[HumN-1]
	_ = x[Vamp-2]
	_ = x[VampN-3]
	_ = x[Woke-4]
	_ = x[WokeN-5]
	_ = x[Zomb-6]
	_ = x[ZombN-7]
	_ = x[E00-8]
	_ = x[E01-9]
	_ = x[E02-10]
	_ = x[E03-11]
	_ = x[E04-12]
	_ = x[E05-13]
	_ = x[E06-14]
	_ = x[E07-15]
	_ = x[S00-16]
	_ = x[S01-17]
	_ = x[S02-18]
	_ = x[S03-19]
	_ = x[S04-20]
	_ = x[S05-21]
	_ = x[S06-22]
	_ = x[S07-23]
	_ = x[S08-24]
	_ = x[S09-25]
	_ = x[S10-26]
	_ = x[S11-27]
	_ = x[S12-28]
	_ = x[S13-29]
	_ = x[S14-30]
	_ = x[S15-31]
	_ = x[S16-32]
	_ = x[S17-33]
	_ = x[S18-34]
	_ = x[S19-35]
	_ = x[S20-36]
	_ = x[S21-37]
	_ = x[S22-38]
	_ = x[S23-39]
	_ = x[S24-40]
	_ = x[S25-41]
	_ = x[S26-42]
	_ = x[S27-43]
	_ = x[S28-44]
	_ = x[S29-45]
	_ = x[S30-46]
	_ = x[S31-47]
	_ = x[S32-48]
	_ = x[S33-49]
	_ = x[S34-50]
	_ = x[S35-51]
	_ = x[S36-52]
	_ = x[S37-53]
	_ = x[S38-54]
	_ = x[S39-55]
	_ = x[S40-56]
	_ = x[S41-57]
	_ = x[S42-58]
	_ = x[S43-59]
	_ = x[S44-60]
	_ = x[S45-61]
	_ = x[S46-62]
	_ = x[S47-63]
	_ = x[S48-64]
	_ = x[S49-65]
	_ = x[S50-66]
	_ = x[S51-67]
	_ = x[S52-68]
	_ = x[S53-69]
	_ = x[S54-70]
	_ = x[S55-71]
	_ = x[S56-72]
	_ = x[S57-73]
	_ = x[S58-74]
	_ = x[S59-75]
	_ = x[S60-76]
	_ = x[S61-77]
	_ = x[S62-78]
	_ = x[S63-79]
}

const _Type_name = "HumHumNVampVampNWokeWokeNZombZombNE00E01E02E03E04E05E06E07S00S01S02S03S04S05S06S07S08S09S10S11S12S13S14S15S16S17S18S19S20S21S22S23S24S25S26S27S28S29S30S31S32S33S34S35S36S37S38S39S40S41S42S43S44S45S46S47S48S49S50S51S52S53S54S55S56S57S58S59S60S61S62S63"

var _Type_index = [...]uint8{0, 3, 7, 11, 16, 20, 25, 29, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97, 100, 103, 106, 109, 112, 115, 118, 121, 124, 127, 130, 133, 136, 139, 142, 145, 148, 151, 154, 157, 160, 163, 166, 169, 172, 175, 178, 181, 184, 187, 190, 193, 196, 199, 202, 205, 208, 211, 214, 217, 220, 223, 226, 229, 232, 235, 238, 241, 244, 247, 250}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
